version: "3.7"

services:
  postgres:
    image: postgres:14.1
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: vps_poc
      POSTGRES_PASSWORD: "9Z55OVUlQrP8WyePn9PfL6j3x9G4lZwM"
    volumes:
      - vps_poc_data:/var/lib/postgresql/data
volumes:
  vps_poc_data:
